### PR TITLE
Tec ui library

### PR DESCRIPTION
**Pull request by famole**
In this pull request we're including the tec-ui interface, this is an early stage of the tec-ui because some of the colors hasn't been delivered by the designers yet.

### CODE REVIEW

**Comment by GriffGreen** [comment]
FOUND THE ISSUE!!! YAYAYAYAY!!!!!

The font! Of course ;-)

**Comment by GriffGreen** [comment]
Closing this week!

**Comment by PJColombo** [comment]
Hey @famole, is this PR an early version of PR #18 ?.  If so, then we can close it, right ?

**Comment by famole** [comment]
Hey @PJColombo I was closing it when i see that you merged the #18, but yes, it's closed now

**Pull request closed without merging**
